var cryptInfo="U2FsdGVkX18XKF9U1+z05wxt/16SNfFtzZMM9livJLSSAmnZWOyKKi2SWQfODuNbFDy0k88SzHi1L9Z1cvSttAreunbSKOdyX6FMwRYuuI2v1ctgzdSxrBJGVrC+f0QJnSHrjuHolFXAWvYfNLG5P9od4bXxCHAtFHnDJgwtYljbsgiDdixZHZYLV6NwplR7rdyHyMeedhcpySkHPFyvll3864PO549StGZ3F9JT8sU=",password_book=function(){this.current_password=this.current_username="";this.data={};this.userInfo={}};
password_book.prototype.init_1=function(a){try{this.data=JSON.parse(CryptoJS.AES.decrypt(cryptInfo,a).toString(CryptoJS.enc.Utf8))}catch(b){return!1}if("Region"in this.data&&"ap-chengdu"==this.data.Region)this.cos=new COS({SecretId:this.data.SecretId,SecretKey:this.data.SecretKey});else return!1;return!0};password_book.prototype.init_2=function(a,b,c){this.current_username=a;this.current_password=b;this.asyncInfo(function(){book.updateDoc();c()})};
password_book.prototype.updateDoc=function(){document.getElementById("uname-display").innerText=this.userInfo.uname;if("infos"in this.userInfo){for(var a=document.getElementById("info-list"),b=a.childNodes,c=b.length-1;0<=c;c--)a.removeChild(b[c]);this.userInfo.infos.forEach(function(d){var e=document.createElement("li");e.innerHTML=d.uname+"\t"+d.passwd+"\t"+d.annotate+"<br>";a.appendChild(e)})}};
password_book.prototype.asyncInfo=function(a){this.cos.getObject({Bucket:this.data.Bucket,Region:this.data.Region,Key:this.current_username},function(b,c){try{book.userInfo=JSON.parse(CryptoJS.AES.decrypt(c.Body,book.current_password).toString(CryptoJS.enc.Utf8)),a()}catch(d){alert(d,"user dont exit")}})};
password_book.prototype.uploadInfo=function(a){book.cos.putObject({Bucket:this.data.Bucket,Region:this.data.Region,Key:this.current_username,StorageClass:"STANDARD",Body:CryptoJS.AES.encrypt(JSON.stringify(this.userInfo),this.current_password).toString(),onProgress:function(b){}},function(b,c){a()})};var book;
function onPreLoginButtonClick(){var a=document.getElementById("pre-login-passwd").value;book=new password_book;book.init_1(a)?(document.getElementById("pre-login-page").style.display="none",document.getElementById("post-login-page").style.display="block"):alert("\u5bc6\u7801\u6709\u8bef")}
function onPostLoginButtonClick(){var a=document.getElementById("post-login-uname").value,b=document.getElementById("post-login-passwd").value;book.init_2(a,b,function(){document.getElementById("post-login-page").style.display="none";document.getElementById("uinfo-display").style.display="block"})}function onRegisterButtonClick(){document.getElementById("post-login-page").style.display="none";document.getElementById("register-page").style.display="block"}var test;
function onRegisterSubmitClick(){book.current_username=document.getElementById("register_uname").value;book.current_password=document.getElementById("register_passwd").value;book.cos.getBucket({Bucket:book.data.Bucket,Region:book.data.Region},function(a,b){b.Contents.forEach(function(c){c.Key==book.current_username&&alert("\u7528\u6237\u540d\u5df2\u5b58\u5728")});book.userInfo={uname:book.current_username,infos:[{uname:book.current_username,passwd:book.current_password,annotate:"password_book"}]};
"Bucket"in book.data&&"Region"in book.data&&book.uploadInfo(function(){document.getElementById("register-page").style.display="none";document.getElementById("post-login-page").style.display="block"})})}
function onAddButtonClick(){var a=document.getElementById("add_uname").value,b=document.getElementById("add_passwd").value,c=document.getElementById("add_annotate").value;"infos"in book.userInfo&&"uname"in book.userInfo?(book.userInfo.infos.push({uname:a,passwd:b,annotate:c}),book.uploadInfo(function(){book.asyncInfo(function(){book.updateDoc()})})):alert("\u8bf7\u91cd\u65b0\u767b")};